notifications:
  slack: cuencafinance:Vb7c4Zn7YCpT0wGjOFDwYQUM
language: python
python: 3.6
sudo: required
services:
- docker
script:
- cp env.template .env
- make travis-test
before_install:
- echo ARCUS_API_KEY=$ARCUS_API_KEY >> .env
