notifications:
  slack: cuencafinance:Vb7c4Zn7YCpT0wGjOFDwYQUM
language: python
python: 3.6
sudo: required
services:
- docker
script:
- cp env.template .env
- echo COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN >> .env
- make travis-test
