notifications:
  slack: cuencafinance:6N0IaVciA0KyNylSTq5ZzW4I
language: python
python: 3.6
sudo: required
services:
- docker
script:
- cp env.template .env
- echo SENTRY_DSN=$SENTRY_DSN >> .env
- make travis-test
