notifications:
  slack: cuencafinance:6N0IaVciA0KyNylSTq5ZzW4I
language: python
python: 3.6
sudo: required
services:
- docker
env:
  global:
    secure: aK7GH99RXDxmkit8/8UondNUeComyjylpZzIHrL83UCSxPHmqpqf5X+xz2mbkS5Jfkf1Xnru/4DLG89MuItpNMgF/T2PtmGIiOfzKunN8e75EH+scCApK2d10bJ6gTaWG1uC059R9NRHwF9YNmcBw8sowr291HAafHKMGOpI/ze9mfMQ2CwomLO7tURPbSrAzHdSZP5+BcRfqHkX9gfQ0da8DCrRg7P6/hZ8N3A0f9EZbgI1PxqsuAMNQXcMvFhWvm/MWwi1F362DlbYQUcua2EAUlIblDF7L3DkQ3yxWLMJyOkKuzwMwr/jMDzegQ9zQpKMzZjb2MkwW5d0gTRZbIG1Wb2M6dZhjS8lrOb9WhL/Wcvpa4/zvZ8qx3NJU4yB6F70eB2hc1pJ0szaJX9g/Eim3ALsa4iIzV75ZFov1p6LmUYwTYs+btb8PH2kqUBTDjCm5V5DU+QKDNxYRANVZl6vUmEEJYBP7A5ePkYuRltIwm1QTp9/P0Q8IhpUFna5dXnvYMyKFamMjU8oPb/a6DpXRe8p+xFi34yNm4Z8pM7m2MxKwF6q69F/rv4tGVN60+IxHBsPIPwfoAvbXHQXZzylSCe52wCUtHO7DX5hKBzGUfcxZrCW71WF4Vb48TL7wgEr4+Bd+UHtehr8VIlyGspNpIetmmjKy2k58tN68pU=
script:
- cp env.template .env
- make travis-test
