version: '3'

services:

  db:
    image: postgres:10.1
    container_name: speid_db
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  stpmex-callback:
    build:
      context: .
      args:
        - AMPQ_ADDRESS=rabbitmq
        - FLASK_ENV=development
    volumes:
      - .:/speid
    ports:
      - 3000:3000
    links:
      - db
      - rabbitmq
    depends_on:
      - db
      - rabbitmq
    env_file:
      - .env