version: '3'

services:

  db:
    image: postgres:10.1

  rabbitmq:
    image: rabbitmq
    ports:
    - 5672:5672
    - 15672:15672

  speid:
    build: .
    tty: true
    volumes:
      - .:/speid
    ports:
    - 3000:3000
    links:
      - db
      - rabbitmq
    depends_on:
      - db
      - rabbitmq
    env_file:
      - .env