version: '3'

services:

  db:
    image: postgres:10.1

  rabbitmq:
    image: rabbitmq

  speid:
    build: .
    tty: true
    ports:
      - 3000:3000
    volumes:
      - .:/speid
    links:
      - db
      - rabbitmq
    depends_on:
      - db
      - rabbitmq
    env_file:
      - .env