version: '3'

services:
  db:
    image: mongo:4.0
    ports:
      - 5672:5672

  rabbitmq:
    image: rabbitmq

  speid:
    build: .
    volumes:
      - .:/speid
    links:
      - db
      - rabbitmq
    depends_on:
      - db
      - rabbitmq
    env_file:
      - .env