"""Add speid_id and change column type

Revision ID: 2773ca239148
Revises: 964df4df01db
Create Date: 2018-10-07 21:19:06.788214

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '2773ca239148'
down_revision = '964df4df01db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions',
                  sa.Column('speid_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'transactions', ['speid_id'])
    op.alter_column('transactions', 'institucion_ordenante',
                    existing_type=sa.Integer(),
                    type_=sa.String())
    op.alter_column('transactions', 'institucion_beneficiaria',
                    existing_type=sa.Integer(),
                    type_=sa.String())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_column('transactions', 'speid_id')
    op.alter_column('transactions', 'institucion_ordenante',
                    existing_type=sa.String(),
                    type_=sa.Integer())
    op.alter_column('transactions', 'institucion_beneficiaria',
                    existing_type=sa.String(),
                    type_=sa.Integer())
    # ### end Alembic commands ###
