"""Add versions to transactions

Revision ID: 964df4df01db
Revises: 0132c2c98aa4
Create Date: 2018-10-06 16:50:34.738942

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '964df4df01db'
down_revision = '0132c2c98aa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions',
                  sa.Column('version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'version')
    # ### end Alembic commands ###
