"""Make estado nullable in transaction

Revision ID: dba57cf901e1
Revises: 20b940497e3e
Create Date: 2018-10-04 20:44:35.364311

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'dba57cf901e1'
down_revision = '20b940497e3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'estado',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'estado',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    # ### end Alembic commands ###
